package com.carebridge.common.error;

public enum ErrorCode {
  VALIDATION_ERROR,
  UNAUTHORIZED,
  FORBIDDEN,
  MUST_CHANGE_PASSWORD,
  NOT_FOUND,
  CONFLICT,
  ILLEGAL_TRANSITION,
  VERSION_CONFLICT,
  INVALID_ASSIGNEE,
  INTERNAL_ERROR
}
